/** Bar
 *  DB_SYSTEMBOLAGET.js
 *  Created by Mauro J. Pappaterra on 17 of 02 2018.
 */

/*DB of Systembolaget saved as an array of objects, each object represents a beverage*/

var DB_SYSTEMBOLAGET = [
    {
        "nr": "10001",
        "artikelid": "25053",
        "varnummer": "100",
        "namn": "Braastad XO",
        "namn2": "",
        "prisinklmoms": "442.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2000-08-07",
        "slutlev": " ",
        "varugrupp": "Cognac",
        "forpackning": "Flaska",
        "forslutning": "Naturkork",
        "ursprung": "Cognac, Fine Champagne",
        "ursprunglandnamn": "Frankrike",
        "producent": "Tiffon",
        "leverantor": "Arcus Sweden AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "40%",
        "modul": "",
        "sortiment": "FS",
        "ekologisk": "0",
        "koscher": "0"
    },
    {
        "nr": "1001",
        "artikelid": "190719",
        "varnummer": "10",
        "namn": "Vanlig Vodka",
        "namn2": "",
        "prisinklmoms": "195.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2006-04-01",
        "slutlev": " ",
        "varugrupp": "Okryddad sprit",
        "forpackning": "Flaska",
        "forslutning": "Skruvkapsyl",
        "ursprung": "",
        "ursprunglandnamn": "Sverige",
        "producent": "Svensk Export Vodka AB",
        "leverantor": "Fondberg",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "37.5%",
        "modul": "",
        "sortiment": "FS",
        "ekologisk": "0",
        "koscher": "0"
    },
    {
        "nr": "1001201",
        "artikelid": "51029",
        "varnummer": "10012",
        "namn": "Dworek Vodka",
        "namn2": "",
        "prisinklmoms": "190.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2004-12-06",
        "slutlev": " ",
        "varugrupp": "Okryddad sprit",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandnamn": "Polen",
        "producent": "Tarpan Fabryka Likierow",
        "leverantor": "TIWA Trading AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "37.5%",
        "modul": "",
        "sortiment": "FS",
        "ekologisk": "0",
        "koscher": "0"
    },
    {
        "nr": "1001202",
        "artikelid": "407506",
        "varnummer": "10012",
        "namn": "Dworek Vodka",
        "namn2": "",
        "prisinklmoms": "100.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2009-10-01",
        "slutlev": " ",
        "varugrupp": "Okryddad sprit",
        "forpackning": "Flaska",
        "forslutning": "Skruvkapsyl",
        "ursprung": "",
        "ursprunglandnamn": "Polen",
        "producent": "Tarpan Fabryka Likierow",
        "leverantor": "TIWA Trading AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "37.5%",
        "modul": "",
        "sortiment": "FS",
        "ekologisk": "0",
        "koscher": "0"
    },
    {
        "nr": "1003802",
        "artikelid": "513291",
        "varnummer": "10038",
        "namn": "Esping Jul B\u00c3\u00a4sk",
        "namn2": "",
        "prisinklmoms": "195.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2010-11-15",
        "slutlev": " ",
        "varugrupp": "Kryddad sprit",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandnamn": "Sverige",
        "producent": "Symposion International",
        "leverantor": "Symposion International AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "32%",
        "modul": "",
        "sortiment": "TSS",
        "ekologisk": "0",
        "koscher": "0"
    },
    {
        "nr": "1004703",
        "artikelid": "723841",
        "varnummer": "10047",
        "namn": "Nils Oscar",
        "namn2": "Celebration Ale",
        "prisinklmoms": "43.70",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2013-02-01",
        "slutlev": " ",
        "varugrupp": "\u00c3\u2013l, Ale",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandnamn": "Sverige",
        "producent": "Nils Oscar Company",
        "leverantor": "The Nils Oscar Company AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "9.4%",
        "modul": "T5",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    },
    {
        "nr": "1004801",
        "artikelid": "733051",
        "varnummer": "10048",
        "namn": "Rhum J. M",
        "namn2": "",
        "prisinklmoms": "729.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2013-03-01",
        "slutlev": " ",
        "varugrupp": "Rom, M\u00c3\u00b6rk",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Martinique",
        "ursprunglandnamn": "Frankrike",
        "producent": "Les Heritiers Crassous de Mede",
        "leverantor": "Cask Sweden AB",
        "argang": "2001",
        "provadargang": "",
        "alkoholhalt": "46.6%",
        "modul": "T7",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    },
    {
        "nr": "1004901",
        "artikelid": "733068",
        "varnummer": "10049",
        "namn": "Rhum J.M",
        "namn2": "",
        "prisinklmoms": "1399.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2013-04-02",
        "slutlev": " ",
        "varugrupp": "Rom, M\u00c3\u00b6rk",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Martinique",
        "ursprunglandnamn": "Frankrike",
        "producent": "Les Heritiers Crassous de Mede",
        "leverantor": "Cask Sweden AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "44.8%",
        "modul": "T7",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    },
    {
        "nr": "1005001",
        "artikelid": "733084",
        "varnummer": "10050",
        "namn": "Balcones Texas",
        "namn2": "",
        "prisinklmoms": "899.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2013-03-01",
        "slutlev": " ",
        "varugrupp": "Whisky, Malt",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandnamn": "USA",
        "producent": "Balcones Distilling",
        "leverantor": "Cask Sweden AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "52.2%",
        "modul": "",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    },
    {
        "nr": "1005101",
        "artikelid": "733200",
        "varnummer": "10051",
        "namn": "Balcones Brimstone",
        "namn2": "",
        "prisinklmoms": "899.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2013-03-01",
        "slutlev": " ",
        "varugrupp": "Whisky, \u00c3\u2013vrig",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandnamn": "USA",
        "producent": "Balcones Distilling",
        "leverantor": "Cask Sweden AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "53.2%",
        "modul": "",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    },
    {
        "nr": "1005201",
        "artikelid": "733236",
        "varnummer": "10052",
        "namn": "Balcones True Blue",
        "namn2": "",
        "prisinklmoms": "899.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2013-03-01",
        "slutlev": " ",
        "varugrupp": "Whisky, \u00c3\u2013vrig",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandnamn": "USA",
        "producent": "Balcones Distilling",
        "leverantor": "Cask Sweden AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "50.2%",
        "modul": "",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    },
    {
        "nr": "1005401",
        "artikelid": "733429",
        "varnummer": "10054",
        "namn": "Linkwood",
        "namn2": "the Octave",
        "prisinklmoms": "1159.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2013-03-01",
        "slutlev": " ",
        "varugrupp": "Whisky, Malt",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Skottland, Highlands, Speyside",
        "ursprunglandnamn": "Storbritannien",
        "producent": "Duncan Taylor Scotch Whisky",
        "leverantor": "Clydesdale AB",
        "argang": "1989",
        "provadargang": "",
        "alkoholhalt": "51.7%",
        "modul": "",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    },
    {
        "nr": "1005502",
        "artikelid": "733446",
        "varnummer": "10055",
        "namn": "Marolo",
        "namn2": "Grappa di Arneis Vigneto Renesio",
        "prisinklmoms": "481.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2013-03-01",
        "slutlev": " ",
        "varugrupp": "Grappa och Marc, Grappa",
        "forpackning": "Flaska",
        "forslutning": "Naturkork",
        "ursprung": "",
        "ursprunglandnamn": "Italien",
        "producent": "Distilleria St Teresa dei Frat",
        "leverantor": "Haugen-Gruppen AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "50%",
        "modul": "T7",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    },
    {
        "nr": "1005602",
        "artikelid": "733468",
        "varnummer": "10056",
        "namn": "Cl\u00c3\u00a9ment",
        "namn2": "Single Cask",
        "prisinklmoms": "529.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2013-04-02",
        "slutlev": " ",
        "varugrupp": "Rom, M\u00c3\u00b6rk",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Martinique",
        "ursprunglandnamn": "Frankrike",
        "producent": "Les Heritiers Crassous de Mede",
        "leverantor": "Cask Sweden AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "47.6%",
        "modul": "T7",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    },
    {
        "nr": "101",
        "artikelid": "1",
        "varnummer": "1",
        "namn": "Renat",
        "namn2": "",
        "prisinklmoms": "203.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "1993-10-01",
        "slutlev": " ",
        "varugrupp": "Okryddad sprit",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandnamn": "Internationellt m\u00c3\u00a4rke",
        "producent": "Pernod Ricard",
        "leverantor": "Pernod Ricard Sweden AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "37.5%",
        "modul": "",
        "sortiment": "FS",
        "ekologisk": "0",
        "koscher": "0"
    },
    {
        "nr": "1010001",
        "artikelid": "817007",
        "varnummer": "10100",
        "namn": "Romano Levi",
        "namn2": "Mostaco d\u00c2\u00b4Asti Donna Selvatica",
        "prisinklmoms": "790.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2014-04-01",
        "slutlev": " ",
        "varugrupp": "Grappa och Marc, Grappa",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandnamn": "Italien",
        "producent": "Distilleria Levi Serafino ( di",
        "leverantor": "Haugen-Gruppen AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "40%",
        "modul": "",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    },
    {
        "nr": "1010404",
        "artikelid": "611864",
        "varnummer": "10104",
        "namn": "Giare 5 Grappe",
        "namn2": "Moscato, Amarone, Teroldego, Chardonnay, Prosecco",
        "prisinklmoms": "399.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2012-03-01",
        "slutlev": " ",
        "varugrupp": "Grappa och Marc, Grappa",
        "forpackning": "5 flaskor \u00c3\u00a0 100 ml",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandnamn": "Italien",
        "producent": "Marzadro",
        "leverantor": "Stragas-Gruppen AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "40%",
        "modul": "",
        "sortiment": "TST",
        "ekologisk": "0",
        "koscher": "0"
    },
    {
        "nr": "1010501",
        "artikelid": "659534",
        "varnummer": "10105",
        "namn": "Genuin 25",
        "namn2": "",
        "prisinklmoms": "149.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2012-09-01",
        "slutlev": " ",
        "varugrupp": "Okryddad sprit",
        "forpackning": "Flaska",
        "forslutning": "Skruvkapsyl",
        "ursprung": "",
        "ursprunglandnamn": "Sverige",
        "producent": "Svensk Vodka i Motala AB",
        "leverantor": "Svensk Vodka i Motala AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "25%",
        "modul": "",
        "sortiment": "TST",
        "ekologisk": "0",
        "koscher": "0"
    },
    {
        "nr": "1011302",
        "artikelid": "723428",
        "varnummer": "10113",
        "namn": "Kullados",
        "namn2": "",
        "prisinklmoms": "499.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2013-04-02",
        "slutlev": " ",
        "varugrupp": "\u00c3\u2013vrig sprit",
        "forpackning": "Flaska",
        "forslutning": "Plastkork\/syntetkork",
        "ursprung": "",
        "ursprunglandnamn": "Sverige",
        "producent": "Kullabygdens Musteri AB",
        "leverantor": "Kullabygdens Destilleri AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "40%",
        "modul": "T5",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    },
    {
        "nr": "1011401",
        "artikelid": "811782",
        "varnummer": "10114",
        "namn": "Grappa Riserva Levi Romano",
        "namn2": "Distilleria Levi Serafino Donna Selvatica",
        "prisinklmoms": "989.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2014-03-01",
        "slutlev": " ",
        "varugrupp": "Grappa och Marc, Grappa",
        "forpackning": "Flaska",
        "forslutning": "Naturkork",
        "ursprung": "",
        "ursprunglandnamn": "Italien",
        "producent": "Distilleria Levi Serafino ( di",
        "leverantor": "Haugen-Gruppen AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "50%",
        "modul": "",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    },
    {
        "nr": "1011601",
        "artikelid": "614078",
        "varnummer": "10116",
        "namn": "Glenmorangie",
        "namn2": "Pride",
        "prisinklmoms": "24500.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2012-02-23",
        "slutlev": " ",
        "varugrupp": "Whisky, Malt",
        "forpackning": "Flaska",
        "forslutning": "Naturkork",
        "ursprung": "Skottland, Highlands, Northern Highlands",
        "ursprunglandnamn": "Storbritannien",
        "producent": "Glenmorangie",
        "leverantor": "Mo\u00c3\u00abt Hennessy Sverige AB",
        "argang": "1981",
        "provadargang": "",
        "alkoholhalt": "56.7%",
        "modul": "",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    },
    {
        "nr": "1011701",
        "artikelid": "734763",
        "varnummer": "10117",
        "namn": "The Arran Malt",
        "namn2": "Orkney Bere",
        "prisinklmoms": "579.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2013-04-02",
        "slutlev": " ",
        "varugrupp": "Whisky, Malt",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Skottland, Highlands, Islands, Arran",
        "ursprunglandnamn": "Storbritannien",
        "producent": "Isle of Arran Distillers",
        "leverantor": "Cask Sweden AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "46%",
        "modul": "T7",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    },
    {
        "nr": "1011901",
        "artikelid": "614800",
        "varnummer": "10119",
        "namn": "Glen Garioch",
        "namn2": "Mackillop's Choice",
        "prisinklmoms": "895.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2012-02-01",
        "slutlev": " ",
        "varugrupp": "Whisky, Malt",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Skottland, Highlands",
        "ursprunglandnamn": "Storbritannien",
        "producent": "Angus Dundee",
        "leverantor": "Philipson S\u00c3\u00b6derberg AB",
        "argang": "1990",
        "provadargang": "",
        "alkoholhalt": "43%",
        "modul": "",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    },
    {
        "nr": "1012601",
        "artikelid": "874805",
        "varnummer": "10126",
        "namn": "Nikka Taketsuru",
        "namn2": "Pure Malt",
        "prisinklmoms": "549.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2014-10-03",
        "slutlev": " ",
        "varugrupp": "Whisky, Malt",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandnamn": "Japan",
        "producent": "The Nikka Whisky Distilling Co",
        "leverantor": "Symposion International AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "43%",
        "modul": "",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    },
    {
        "nr": "1013104",
        "artikelid": "734572",
        "varnummer": "10131",
        "namn": "Poli Grappa Barrel Pack",
        "namn2": "",
        "prisinklmoms": "549.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2013-04-02",
        "slutlev": " ",
        "varugrupp": "Grappa och Marc, Grappa",
        "forpackning": "5 flaskor \u00c3\u00a0 100 ml",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandnamn": "Italien",
        "producent": "Distillerie Poli",
        "leverantor": "Bibendum",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "40%",
        "modul": "T7",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    },
    {
        "nr": "1013201",
        "artikelid": "633539",
        "varnummer": "10132",
        "namn": "Linkwood",
        "namn2": "Duthies 23 Years",
        "prisinklmoms": "950.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2012-03-01",
        "slutlev": " ",
        "varugrupp": "Whisky , Malt",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Skottland, Highlands, Speyside",
        "ursprunglandnamn": "Storbritannien",
        "producent": "William Cadenhead",
        "leverantor": "Symposion International AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "46%",
        "modul": "T7",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    },
    {
        "nr": "1013901",
        "artikelid": "871188",
        "varnummer": "10139",
        "namn": "Longmorn",
        "namn2": "16 Years",
        "prisinklmoms": "1095.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2014-10-03",
        "slutlev": " ",
        "varugrupp": "Whisky, Malt",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Skottland",
        "ursprunglandnamn": "Storbritannien",
        "producent": "Sansibar Whisky",
        "leverantor": "Symposion International AB",
        "argang": "1997",
        "provadargang": "",
        "alkoholhalt": "48.5%",
        "modul": "",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    },
    {
        "nr": "1014002",
        "artikelid": "634582",
        "varnummer": "10140",
        "namn": "Braunstein",
        "namn2": "Library Collection 11:1",
        "prisinklmoms": "999.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2012-03-01",
        "slutlev": " ",
        "varugrupp": "Whisky, Malt",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandnamn": "Danmark",
        "producent": "Bryghuset Braunstein",
        "leverantor": "Galatea Spirits AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "46%",
        "modul": "",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    },
    {
        "nr": "1014301",
        "artikelid": "734788",
        "varnummer": "10143",
        "namn": "Waqar Pisco",
        "namn2": "",
        "prisinklmoms": "449.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2013-04-02",
        "slutlev": " ",
        "varugrupp": "Brandy och Vinsprit, Vinsprit",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandnamn": "Chile",
        "producent": "Tulahu\u00c3\u00a9n",
        "leverantor": "N57 Nordic AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "40%",
        "modul": "",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    },
    {
        "nr": "1014804",
        "artikelid": "638540",
        "varnummer": "10148",
        "namn": "Esprit Calvados 5 domaines",
        "namn2": "",
        "prisinklmoms": "695.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2012-04-02",
        "slutlev": " ",
        "varugrupp": "Calvados",
        "forpackning": "5 flaskor \u00c3\u00a0 100 ml",
        "forslutning": "",
        "ursprung": "Normandie, Calvados, Calvados du Pays d'",
        "ursprunglandnamn": "Frankrike",
        "producent": "Esprit Calvados 5 domaines",
        "leverantor": "Symposion International AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "42%",
        "modul": "",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    },
    {
        "nr": "1015001",
        "artikelid": "638546",
        "varnummer": "10150",
        "namn": "The Spice Tree",
        "namn2": "",
        "prisinklmoms": "499.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2012-04-02",
        "slutlev": " ",
        "varugrupp": "Whisky , Malt",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Skottland",
        "ursprunglandnamn": "Storbritannien",
        "producent": "Compass Box",
        "leverantor": "Symposion International AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "46%",
        "modul": "T7",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    },
    {
        "nr": "1015101",
        "artikelid": "707630",
        "varnummer": "10151",
        "namn": "Grappa di Levi",
        "namn2": "Levi Romano",
        "prisinklmoms": "3446.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2012-12-01",
        "slutlev": " ",
        "varugrupp": "Grappa och Marc, Grappa",
        "forpackning": "Flaska",
        "forslutning": "Naturkork",
        "ursprung": "",
        "ursprunglandnamn": "Italien",
        "producent": "Levi Romano",
        "leverantor": "Haugen-Gruppen AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "50%",
        "modul": "",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    },
    {
        "nr": "1015301",
        "artikelid": "723096",
        "varnummer": "10153",
        "namn": "Highland Park",
        "namn2": "Norse Gods Loki",
        "prisinklmoms": "1399.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2013-04-02",
        "slutlev": " ",
        "varugrupp": "Whisky, Malt",
        "forpackning": "Flaska",
        "forslutning": "Naturkork",
        "ursprung": "Skottland, Highlands, Islands, Orkney",
        "ursprunglandnamn": "Storbritannien",
        "producent": "Highland Park",
        "leverantor": "Edrington Sweden AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "48.7%",
        "modul": "T5",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    },
    {
        "nr": "1015601",
        "artikelid": "828902",
        "varnummer": "10156",
        "namn": "Bocchino Riserva Cantina Privata",
        "namn2": "18 Years",
        "prisinklmoms": "749.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2014-05-02",
        "slutlev": " ",
        "varugrupp": "Grappa och Marc, Grappa",
        "forpackning": "Flaska",
        "forslutning": "Plastkork\/syntetkork",
        "ursprung": "",
        "ursprunglandnamn": "Italien",
        "producent": "Distilleria Bocchino",
        "leverantor": "Brandpartners AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "45%",
        "modul": "",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    },
    {
        "nr": "1015701",
        "artikelid": "611207",
        "varnummer": "10157",
        "namn": "Lustau Brandy Solera",
        "namn2": "Gran Reserva Finest Selection",
        "prisinklmoms": "499.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2012-02-01",
        "slutlev": " ",
        "varugrupp": "Brandy och Vinsprit, Brandy",
        "forpackning": "Flaska",
        "forslutning": "Naturkork",
        "ursprung": "",
        "ursprunglandnamn": "Spanien",
        "producent": "Lustau",
        "leverantor": "Hjo Grosshandel AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "40%",
        "modul": "T7",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    },
    {
        "nr": "1015902",
        "artikelid": "854266",
        "varnummer": "10159",
        "namn": "Facile",
        "namn2": "Arrak",
        "prisinklmoms": "179.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2014-06-02",
        "slutlev": " ",
        "varugrupp": "\u00c3\u2013vrig sprit",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandnamn": "Sverige",
        "producent": "Facile & Co",
        "leverantor": "Facile & Co AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "40%",
        "modul": "",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    },
    {
        "nr": "1016101",
        "artikelid": "633586",
        "varnummer": "10161",
        "namn": "Benriach",
        "namn2": "Liquid Sun 15 Years",
        "prisinklmoms": "799.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2012-03-01",
        "slutlev": " ",
        "varugrupp": "Whisky, Malt",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Skottland, Highlands, Speyside",
        "ursprunglandnamn": "Storbritannien",
        "producent": "Liquid Sun Whisky",
        "leverantor": "Symposion International AB",
        "argang": "1996",
        "provadargang": "",
        "alkoholhalt": "46%",
        "modul": "",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    },
    {
        "nr": "1016301",
        "artikelid": "639227",
        "varnummer": "10163",
        "namn": "Littlemill",
        "namn2": "Liquid Sun 22 Years",
        "prisinklmoms": "1399.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2012-04-19",
        "slutlev": " ",
        "varugrupp": "Whisky, Malt",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Skottland, Lowlands",
        "ursprunglandnamn": "Storbritannien",
        "producent": "Ehrlich & Schneider Gbr.",
        "leverantor": "Symposion International AB",
        "argang": "1989",
        "provadargang": "",
        "alkoholhalt": "52.2%",
        "modul": "T7",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    },
    {
        "nr": "1016501",
        "artikelid": "639258",
        "varnummer": "10165",
        "namn": "Compass Box",
        "namn2": "Hedonism",
        "prisinklmoms": "725.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2012-04-02",
        "slutlev": " ",
        "varugrupp": "Whisky, Grain",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "Skottland",
        "ursprunglandnamn": "Storbritannien",
        "producent": "Compass Box",
        "leverantor": "Symposion International AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "43%",
        "modul": "",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    },
    {
        "nr": "1016601",
        "artikelid": "639416",
        "varnummer": "10166",
        "namn": "Eau-de-Vie de Prune",
        "namn2": "",
        "prisinklmoms": "549.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2012-04-02",
        "slutlev": " ",
        "varugrupp": "Sprit av frukt",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandnamn": "Frankrike",
        "producent": "Etienne Brana",
        "leverantor": "Divine AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "42%",
        "modul": "",
        "sortiment": "TSE",
        "ekologisk": "0",
        "koscher": "0"
    }
]