var DB_SPECIALSTOCK =
 [
     {
    "article_id": "MIKE01", 
    "name": "mike's Robust Imperial Porter",
    "beer": true,
    "wine": false,
    "spirit": false,
    "year": null,
    "country": "England",
    "volume_ml": 330,
    "alcohol_percentage": 8.0,
    "sale_price": 50.0,
    "in_stock": 30,
    "kosher": false,
    "ecologic": false,
    "special": true
},

{
    "article_id": "MIKE02", 
    "name": "Taranaki IPA",
    "beer": true,
    "wine": false,
    "spirit": false,
    "year": null,
    "country": "New Zeland",
    "volume_ml": 350,
    "alcohol_percentage": 7.0,
    "sale_price": 65.0,
    "in_stock": 10,
    "kosher": false,
    "ecologic": false,
    "special": true
},

{
    "article_id": "MIKE03",
    "name": "Vanilla Coffee Porter",
    "beer": true,
    "wine": false,
    "spirit": false,
    "year": null,
    "country": "France",
    "volume_ml": 500,
    "alcohol_percentage": 8.0,
    "sale_price": 200.0,
    "in_stock": 5,
    "kosher": false,
    "ecologic": false,
    "special": true
},
{
    "article_id": "MIKE04",
    "name": "Chocolate Milk Stout",
    "beer": true,
    "wine": false,
    "spirit": false,
    "year": null,
    "country": "England",
    "volume_ml": 330,
    "alcohol_percentage": 8.0,
    "sale_price": 150.0,
    "in_stock": 15,
    "kosher": false,
    "ecologic": false,
    "special": true
},
{
    "article_id": "MIKE05",
    "name": "Onemorepaleale",
    "beer": true,
    "wine": false,
    "spirit": false,
    "year": null,
    "country": "England",
    "volume_ml": 330,
    "alcohol_percentage": 5.5,
    "sale_price": 120.0,
    "in_stock": 25,
    "kosher": false,
    "ecologic": false,
    "special": true
},
{
    "article_id": "MIKE06",
    "name": "PilS-NAH",
    "beer": true,
    "wine": false,
    "spirit": false,
    "year": null,
    "country": "New Zeland",
    "volume_ml": 330,
    "alcohol_percentage": 5.0,
    "sale_price": 165.0,
    "in_stock": 3,
    "kosher": false,
    "ecologic": false,
    "special": true
},
{
    "article_id": "MIKE07",
    "name": "Longline Lager",
    "beer": true,
    "wine": false,
    "spirit": false,
    "year": null,
    "country": "Eurpoe",
    "volume_ml": 330,
    "alcohol_percentage": 5.0,
    "sale_price": 175.0,
    "in_stock": 17,
    "kosher": false,
    "ecologic": false,
    "special": true
},
{
    "article_id": "MIKE08",
    "name": "Mild Ale",
    "beer": true,
    "wine": false,
    "spirit": false,
    "year": null,
    "country": "Eurpoe",
    "volume_ml": 330,
    "alcohol_percentage": 4.0,
    "sale_price": 145.0,
    "in_stock": 25,
    "kosher": false,
    "ecologic": true,
    "special": true
},
{
    "article_id": "MIKE09",
    "name": " Full Nelson IPA",
    "beer": true,
    "wine": false,
    "spirit": false,
    "year": null,
    "country": "New Zeland",
    "volume_ml": 330,
    "alcohol_percentage": 7.0,
    "sale_price": 145.0,
    "in_stock": 25,
    "kosher": false,
    "ecologic": false,
    "special": true
},
{
    "article_id": "MIKE10",
    "name": " Second Coming IIPA",
    "beer": true,
    "wine": false,
    "spirit": false,
    "year": null,
    "country": "New Zeland",
    "volume_ml": 330,
    "alcohol_percentage": 9.0,
    "sale_price": 145.0,
    "in_stock": 20,
    "kosher": false,
    "ecologic": true,
    "special": true
},
{
    "article_id": "MIKE11",
    "name": " Surf Spot X",
    "beer": true,
    "wine": false,
    "spirit": false,
    "year": null,
    "country": "New Zeland",
    "volume_ml": 330,
    "alcohol_percentage": 5.7,
    "sale_price": 115.0,
    "in_stock": 25,
    "kosher": false,
    "ecologic": false,
    "special": true
},
{
    "article_id": "MIKE12",
    "name": "Boys N Girls",
    "beer": true,
    "wine": false,
    "spirit": false,
    "year": null,
    "country": "New Zeland",
    "volume_ml": 330,
    "alcohol_percentage": 8.0,
    "sale_price": 125.0,
    "in_stock": 2,
    "kosher": false,
    "ecologic": false,
    "special": true
},
{
    "article_id": "MIKE13",
    "name": "Hopstock & 2 Smoking Barrels",
    "beer": true,
    "wine": false,
    "spirit": false,
    "year": null,
    "country": "New Zeland",
    "volume_ml": 330,
    "alcohol_percentage": 5.0,
    "sale_price": 125.0,
    "in_stock": 0,
    "kosher": false,
    "ecologic": false,
    "special": true
},
{
    "article_id": "MIKE14",
    "name": "Damson in Distress",
    "beer": true,
    "wine": false,
    "spirit": false,
    "year": null,
    "country": "England",
    "volume_ml": 330,
    "alcohol_percentage": 5.0,
    "sale_price": 170.0,
    "in_stock": 0,
    "kosher": false,
    "ecologic": false,
    "special": true
},
{
    "article_id": "MIKE15",
    "name": "Flight of the Falcon",
    "beer": true,
    "wine": false,
    "spirit": false,
    "year": 2010,
    "country": "New Zeland",
    "volume_ml": 330,
    "alcohol_percentage": 5.7,
    "sale_price": 185.0,
    "in_stock": 8,
    "kosher": false,
    "ecologic": false,
    "special": true
}
,
{
    "article_id": "MIKE16",
    "name": "Leaky Boat",
    "beer": true,
    "wine": false,
    "spirit": false,
    "year": 2014,
    "country": "USA",
    "volume_ml": 330,
    "alcohol_percentage": 5.2,
    "sale_price": 145.0,
    "in_stock": 17,
    "kosher": false,
    "ecologic": false,
    "special": true
}


]
;

